### ISSUE TITLE
Produces incorrect output on big-endian systems.

### ISSUE THREAD

**Issue by oyvindln** [Frommi/miniz_oxide#11]
At least decompression of raw blocks and compression doesn't work.
Tested using [cross](https://github.com/japaric/cross)
E.g tests run fine on mips64el, but not mips64 `deflate::test::compress_small` and `inflate::tinfl_oxide::test::raw_block` are failing with incorrect output. Haven't tested the C API yet.

Working on fixing it.

**Comment by Frommi** [comment]
Heads up that trailing_zeros need to become leading_zeros in BE (it's okay that only byte order changes, but not bit order because we divide by 8 afterwards):
https://github.com/Frommi/miniz_oxide/blob/master/miniz_oxide/src/deflate/tdef_oxide.rs#L1144
https://github.com/Frommi/miniz_oxide/blob/master/miniz_oxide/src/deflate/tdef_oxide.rs#L1798

**Comment by oyvindln** [comment]
It seems decompression works fine. The failure was just a bug in the test itself which I fixed.
