### ISSUE TITLE
dependency on the alloc crate should be optional.

### ISSUE THREAD

**Issue by Lokathor** [Frommi/miniz_oxide#111]
It seems like the core decompression routines can be performed without allocating at all.

We should make the use of the `alloc` crate optional behind a cargo feature, though this would be a breaking release to do so.

**Comment by oyvindln** [comment]
Yeah that seems reasonable.

**Comment by mkeeter** [comment]
I've implemented this in a [`with-alloc` branch here](https://github.com/oxidecomputer/miniz_oxide/tree/with-alloc):

- The `with-alloc` feature is enabled by default
- When not enabled, the crate skips `deflate` and a few parts of `inflate` that require allocation

Happy to open a PR, if you're willing to bring it in!

**Comment by mkeeter** [comment]
Yeah, I wasn't totally sure about whether this would be breaking, and the [docs](https://doc.rust-lang.org/cargo/reference/semver.html#minor-adding-a-new-cargo-feature) didn't say anything about "adding a new feature and making it enabled by default".

I _think_ it would only break in cases where people import the library with `default-features = false`.  Doing so would be a no-op until this change, since there weren't any default features!

Anyways, I've bumped the version, added some docs, and opened a PR [here](https://github.com/Frommi/miniz_oxide/pull/117).

Ironically, after testing it out, I'm probably _not_ going to use it in my embedded system: it reduces a compressed object's size by 9.7K, but adds 11.5K of code to decompress it, for a slight net size _increase_ 😅

**Comment by dancrossnyc** [comment]
Regardless of Matt's use case, I would love to see this integrated. :-)

**Comment by oyvindln** [comment]
yeah it's been merged in, just not in a release yet as I wanted to look at a few API tweaks for a version bumps.

**Comment by dancrossnyc** [comment]
> yeah it's been merged in, just not in a release yet as I wanted to look at a few API tweaks for a version bumps.

Uh, I totally didn't miss that or anything. :-)

Thanks! I'm excited for the new release.

**Comment by oyvindln** [comment]
Released now, would probably be doable to do the same with compression later if there is interest.
