### ISSUE TITLE
`adler` is archived

### ISSUE THREAD

**Issue by smoelius** [Frommi/miniz_oxide#148]
As of yesterday, it seems: https://github.com/jonas-schievink/adler

EDIT: `adler` is relied upon here: https://github.com/Frommi/miniz_oxide/blob/79307d7bd6e4aa3e86b30fd225a00ecb412188a4/miniz_oxide/Cargo.toml#L20

**Comment by oyvindln** [comment]
Hm. I don't know whether this is an issue or not. There aren't really any alternatives atm as simd-adler32 uses unsafe (due to the use of manual SIMD code) hence why it's an optional feature, and the reason we moved to the adler crate from adler32 originally was [due](https://github.com/Frommi/miniz_oxide/pull/83) to licensing differences. (The adler32 git has it's last update even further back.)

I guess we'd need to fork it or ask if it would be possible to take over the crate or something if an update is be needed. Judging by the benches at the [simd-adler32](https://crates.io/crates/simd-adler32) page it's possible there are some performance improvements that could be done even if explicit SIMD can't be used due to unsafe. (ofc using the simd feature which uses simd-adler32 will speed up things more if that's important, and one is using the zlib wrapper specifically.)

For that matter miniz_oxide could probably benefit being moved/transfered to an org or something as well as I'm basically the sole maintainer currently, not sure if @Frommi is accessible these days.

**Comment by smoelius** [comment]
> For that matter miniz_oxide could probably benefit being moved/transfered to an org or something

FWIW, `minuz_oxide` appears in my projects' dependency trees under [`anyhow`](https://github.com/dtolnay/anyhow) >> [`backtrace`](https://github.com/rust-lang/backtrace-rs/tree/master) and [`gix`](https://github.com/Byron/gitoxide) >> ... >> [`flate2`](https://github.com/rust-lang/flate2-rs).

> ... I'm basically the sole maintainer currently ...

Thank you for that! :pray:

**Comment by jayvdb** [comment]
I've mentioned this issue and general problem at https://github.com/rustsec/advisory-db/issues/1992

**Comment by GnomedDev** [comment]
Should this be closed now, as it seems like adler2 is being depended on?

**Comment by oyvindln** [comment]
Yup, just forgot to add it to the commits
