### ISSUE TITLE
Zip broken for 0.3.4?

### ISSUE THREAD

**Issue by chrisduerr** [Frommi/miniz_oxide#63]
I was looking into a build failure on CI and noticed that a build command is panicking when trying to extract a zip archive. It seems to be failing at [this](https://github.com/Frommi/miniz_oxide/blob/0ea3474172dcb0713c292d5cc0bea1361f4d88f3/miniz_oxide/src/inflate/core.rs#L1541-L1544) assertion.

Looking at the diff that introduced this change, I found the following comment:

https://github.com/Frommi/miniz_oxide/commit/2a5703a4de8557dcbac981a52ea7cb1e414a169b#diff-1b531c5e405e0bc95890d52cf2f2f5b5R44

> zip is broken right now due to struct difference between c and rust version

That makes it sound like ZIP is not supported in the latest release. Is this correct?  In a non-breaking release this is likely to break a lot of things downstream, which will only be noticed at runtime.

Downgrading to 0.3.3 fixes this problem.

**Comment by oyvindln** [comment]
The zip being referred to in that comment is [this](https://github.com/Frommi/miniz_oxide/blob/master/tests/miniz_tester.cpp#L856) test function not working right now due to the struct definition in the C header not matching the rust one. That's already been broken for a few releases now, I just disabled the test for it in the latest commit so our CI would work fine again.

The assertion is unrelated to that, but if it fails when it's not supposed to I'll remove it and upload a new version.

**Comment by chrisduerr** [comment]
Thanks!
